### PR TITLE
Added support for Vuforia AR

### LINKED ISSUE #28: ARCamera compatibility?
Question: Can your UnityBarcodeScanner work with ARCamera from Vuforia? It works wonders in normal mode, how can I use it for ARCamera?

### PR DESCRIPTION
**Pull request by maximetinu**
Hi,

I've modified your asset to make it work with the Vuforia webcam. I made it by directly inheriting your IWebcam interface, so it works properly with the rest of the classes.

Fixes [#28](https://github.com/kefniark/UnityBarcodeScanner/issues/28)

### CODE REVIEW

**Comment by yosun** [comment]
Hmm, can this be updated to the current IWebcam interface?

**Comment by yosun** [comment]
Assets/Plugins/UnityBarcodeScanner/Webcam/VuforiaCamera.cs(19,18): error CS0535: `BarcodeScanner.Webcam.VuforiaCamera' does not implement interface member `BarcodeScanner.IWebcam.GetRotation()'


etc

**Comment by daoth90** [comment]
> Assets/Plugins/UnityBarcodeScanner/Webcam/VuforiaCamera.cs(19,18): error CS0535: `BarcodeScanner.Webcam.VuforiaCamera' does not implement interface member `BarcodeScanner.IWebcam.GetRotation()'
> 
> etc

Hi, can you get it to work?

**Comment by daoth90** [comment]
I just implement some missing interface methods, and it still works. Thanks

**Pull request closed without merging**
